config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post 'users/validate', to: 'users/registrations#validate', as: 'validate'
  end

  devise_for :users
  
  get 'archives' => 'archives#index'
  get 'categories' => 'categories#index'

  post 'validate' => 'users/users#validate'
  resources :users do
    resources :articles
  end

  resources :articles do
    resources :comments, only: [:create]
  end

  post 'favorite' => 'favorites#favorite'

  root 'articles#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
  <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">My Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to t('application.home'), root_path %> <span class="sr-only">(current)</span></a></li>
        <!--li><a href="#">Link</a></li-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('application.categories') %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% category_list.each do |cat| -%>
              <li><%= link_to cat.name, categories_path(cat_id: cat.id) %></li>
            <% end -%>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left" role="search" action="/articles">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="key_word">
        </div>
        <button type="submit" class="btn btn-default"><%= t('application.search_button') %></button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <!--li><a href="#">Link</a></li-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>    
            Wlecome <%= current_user.email %>
          <% else %>
            <%= t('application.sign_in') %> 
          <% end %>
          <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <% if user_signed_in? %>    
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to('Change password', edit_registration_path(:user)) %></li>
            <% else %>    
              <li><%= link_to 'Log in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>  
            <% end %>    
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<span class="notice"><%= notice %></span>
<!--span class="alert"><%#= alert %></span-->

<div class="col-sm-8 blog-main">
  
  <%= yield %>
</div>

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4><%= t('application.about') %></h4>
            <p> <em>My Blog</em> is a program based on Ruby on Rails, this is a blog about software development. </p>
          </div><br>
          <div class="sidebar-module">
            <h4><%= t('application.archives') %></h4>
            <ol class="list-unstyled">
              <% archive_months.reverse.each do |item| -%>
                <li><%= link_to item.ym_name, archives_path(ym_code: item.ym_code) %></li>
              <% end -%>
            </ol>
          </div><br>
          <div class="sidebar-module">
            <h4><%= t('application.elsewhere') %></h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div><br>
        </div><!-- /.blog-sidebar -->


</div>

</body>
</html>